ACTUATOR:
  THROTTLE_FORWARD_PWM: 410
  THROTTLE_STOPPED_PWM: 384
  THROTTLE_REVERSE_PWM: 310
  THROTTLE_KICK_PULSE: 410
  THROTTLE_KICK_LENGTH: 4
  THROTTLE_FULLSPEED_PULSE: 420
  THROTTLE_BRAKE_PULSE: 400
  THROTTLE_MIN_SPD_PULSE: 395
  THROTTLE_CONSTANT_MODE: 0
  FULLSPEED_DECISION_THRESH: 0.8
  FULLSPEED_HYSTERESIS_LENGTH: 5
  