DEBUG:
  LEVEL: "INFO"
  PARTS:
    MAIN:
      NAME: "donkey.manage"
      LEVEL: "INFO"
    PERFMON:
      NAME: "donkey.perfmon"
      LEVEL: "INFO"
      FILE: "./perfmon.txt"
    PERFDUMP:
      NAME: "donkey.perfdump"
      LEVEL: "INFO"
      TIMEOUT: 30
    TRACER:
      FILE: "./trace.log"
    TXCTRL:
      NAME: "donkey.txctrl"
      LEVEL: "INFO"
    CAMERA:
      NAME: "donkey.camera"
      LEVEL: "INFO"
    ACT-THROTTLE:
      NAME: "donkey.act-throttle"
      LEVEL: "INFO"
    ACT-STEERING:
      NAME: "donkey.act-steering"
      LEVEL: "INFO"
  
MODEL:
  MODEL_IN_USE: 0

ACTUATOR:
  THROTTLE_FORWARD_PWM: 410
  THROTTLE_STOPPED_PWM: 384
  THROTTLE_REVERSE_PWM: 310
  THROTTLE_KICK_PULSE: 410
  THROTTLE_KICK_LENGTH: 4
  THROTTLE_FULLSPEED_PULSE: 420
  THROTTLE_BRAKE_PULSE: 370
  THROTTLE_MIN_SPD_PULSE: 395
  THROTTLE_CONSTANT_MODE: 0
  FULLSPEED_DECISION_THRESH: 0.8
  FULLSPEED_HYSTERESIS_LENGTH: 5
  BRAKE_DECISION_THRESH: 0.8
  BRAKE_HYSTERESIS_LENGTH: 5
  
TX:
  TX_THROTTLE_MIN: 913
  TX_THROTTLE_MAX: 2111
  TX_STEERING_MIN: 960
  TX_STEERING_MAX: 2060
  TX_THROTTLE_TRESH: 1470
  TX_CH_AUX_TRESH: 1500
  TX_SPEEDOMETER_MIN: 1000
  TX_SPEEDOMETER_MAX: 8000
  TX_SERIAL: /dev/ttyS2
